site_name: SC-machine
pages:
  - Home: index.md
  - Build:
    - Build on Linux: build/linux-build.md
    - Build on Windows: build/windows-build.md
  - Development:
    - Git-workflow: dev/git-workflow.md
    - Pull requets: dev/pr.md
    - Codestyle: dev/codestyle.md
    - Unit tests: dev/test.md
  - API:
    - Meta programming: cpp/cpp-meta.md
    - Agents: cpp/kpm.md
    - Template: cpp/templates.md
    - Common: cpp/common.md
    - Python: python/python.md
  - Common:
    - Element types: cpp/el_types.md
    - Configuration files: other/config.md
    - Sctp-protocol: net/sctp.md
    - SCs language: other/scs.md
  - License: license.md
  - Changelog: changelog.md
  - Thirdparty: thirdparty.md

theme: readthedocs

markdown_extensions:
  - markdown_include.include
